name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@master
        id: cacheNodeModules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: yarn install
      - run: yarn test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cronicle_host: ${{ secrets.CRONICLE_URL }}
          event_id: ${{ secrets.EVENT_ID }}
          api_key: ${{ secrets.API_KEY }}
